export const API_ERROR = 'EVENT/API_ERROR_RECIEVED';
export const RECIEVED_TUBING = 'EVENT/RECIEVED_TUBING';
export const RECIEVED_WATER = 'EVENT/RECIEVED_WATER';
export const FETCHING_WATER = 'EVENT/FETCHING_WATER';
export const RECIEVED_OIL = 'EVENT/RECIEVED_OIL';
export const RECIEVED_INJ_VALVE = 'EVENT/RECIEVED_INJ_VALVE';
export const RECIEVED_FLARE = 'EVENT/RECIEVED_FLARE';
export const RECIEVED_CASING = 'EVENT/RECIEVED_FLARE';
export const FETCH_METRICS = 'EVENT/FETCH_METRICS';

export default {
    API_ERROR,
    RECIEVED_CASING,
    RECIEVED_TUBING,
    RECIEVED_WATER,
    RECIEVED_FLARE,
    RECIEVED_INJ_VALVE,
    FETCH_METRICS,
    FETCHING_WATER,
}