const API_ERROR = 'EVENT/API_ERROR_RECIEVED';
const RECIEVED_TUBING = 'EVENT/RECIEVED_TUBING';
const RECIEVED_WATER = 'EVENT/RECIEVED_WATER';
const RECIEVED_OIL = 'EVENT/RECIEVED_OIL';
const RECIEVED_INJ_VALVE = 'EVENT/RECIEVED_INJ_VALVE';
const RECIEVED_FLARE = 'EVENT/RECIEVED_FLARE';
const RECIEVED_CASING = 'EVENT/RECIEVED_FLARE';
const FETCH_METRICS = 'EVENT/FETCH_METRICS';